spring:
  activemq:
    inner:
      broker-url: tcp://127.0.0.1:61616
      user: admin
      password: admin
    saas:
      broker-url: tcp://127.0.0.1:61618
      user: admin
      password: admin
